DROP TABLE IF EXISTS "Computer";
CREATE TABLE "Computer" ("ID" INTEGER PRIMARY KEY  NOT NULL ,"ComputerName" VARCHAR NOT NULL  DEFAULT (null) ,"Year" INTEGER NOT NULL ,"Type" VARCHAR,"Built" VARCHAR);
DROP TABLE IF EXISTS "People";
CREATE TABLE "People" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "Name" VARCHAR NOT NULL , "Gender" VARCHAR NOT NULL , "Birth" INTEGER NOT NULL , "Death" INTEGER);
