DROP TABLE IF EXISTS "Computer";
<<<<<<< HEAD
CREATE TABLE "Computer" ("CompID" INTEGER PRIMARY KEY  NOT NULL , "CompName" TEXT NOT NULL , "CompYear" INTEGER NOT NULL , "CompType" TEXT, "CompBuilt" CHAR);
DROP TABLE IF EXISTS "Scientist";
CREATE TABLE "Scientist" ("Name" TEXT PRIMARY KEY  NOT NULL  DEFAULT (null) ,"Gender" CHAR NOT NULL ,"Birth" INTEGER NOT NULL ,"Death" INTEGER);
=======
CREATE TABLE "Computer" ("ID" INTEGER PRIMARY KEY  NOT NULL ,"ComputerName" VARCHAR NOT NULL  DEFAULT (null) ,"Year" INTEGER NOT NULL ,"Type" VARCHAR,"Built" VARCHAR);
DROP TABLE IF EXISTS "People";
CREATE TABLE "People" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "Name" VARCHAR NOT NULL , "Gender" VARCHAR NOT NULL , "Birth" INTEGER NOT NULL , "Death" INTEGER);
>>>>>>> 4d2badfa9171ae3889bbc9f1979cc46040b61fd4
