DROP TABLE IF EXISTS "Computer";
CREATE TABLE "Computer" ("CompID" INTEGER PRIMARY KEY  NOT NULL , "CompName" TEXT NOT NULL , "CompYear" INTEGER NOT NULL , "CompType" TEXT, "CompBuilt" CHAR);
DROP TABLE IF EXISTS "Scientist";
CREATE TABLE "Scientist" ("Name" TEXT PRIMARY KEY  NOT NULL  DEFAULT (null) ,"Gender" CHAR NOT NULL ,"Birth" INTEGER NOT NULL ,"Death" INTEGER);
