DROP TABLE IF EXISTS "Computers";
CREATE TABLE "Computers" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "ComputerName" VARCHAR NOT NULL , "Year" INTEGER NOT NULL , "Type" VARCHAR, "Built" INTEGER);
DROP TABLE IF EXISTS "People";
CREATE TABLE "People" ("ID" INTEGER PRIMARY KEY  NOT NULL ,"Name" VARCHAR NOT NULL ,"Gender" CHAR NOT NULL  DEFAULT (null) ,"Birth" INTEGER NOT NULL ,"Death" INTEGER);
INSERT INTO "People" VALUES(1,'Harpa Reynisdóttir','Female',1978,NULL);
